version: "3"

# Requires expose TOKEN=[[PARTICLE-TOKEN]]
services:

  prometheus:
    image: prom/prometheus
    volumes:
    - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    expose:
    - "9090" # Default HTTP Endpoint
    ports:
    - 9090:9090
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - "http://prometheus:9090/-/healthy"
  
  particle-exporter:
    image: dazwilkin/particle-exporter@sha256:61edf2a6e81548c5e53f3b5885fb1e5c25dd83e0251466dc1940cf68e7706399
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
    - --token=${TOKEN}
    expose:
    - "9999"
    ports:
    - 9999:9999
    healthcheck:
      test:
      - CMD
      - /healthcheck
      - "http://particle-exporter:9999/healthz"