version: "3"

# Requires expose TOKEN=[[PARTICLE-TOKEN]]
services:

  prometheus:
    image: prom/prometheus
    volumes:
    - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    expose:
    - "9090" # Default HTTP Endpoint
    ports:
    - 9090:9090
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - "http://prometheus:9090/-/healthy"
  
  particle-exporter:
    image: dazwilkin/particle-exporter@sha256:a1c6b370bbe7afd60cebbefcfad54922c4f767a0c566b2410745acee26993120
    command:
    - --token=${TOKEN}
    expose:
    - "9999"
    ports:
    - 9999:9999
