global:
  scrape_interval: 5s
  external_labels:
    monitor: "local-monitor"
scrape_configs:
  - job_name: "particle-exporter"
    honor_labels: true
    static_configs:
      - targets: ["particle-exporter:9999"]